# Game States
STARTUP = 0
MAIN_MENU = 1
MAIN_GAME = 2
GAME_WIDTH = 640
GAME_HEIGHT = 360
LEVEL_WIDTH, LEVEL_HEIGHT = 320, 180
TILE_SIZE = 40

SPRITE_WIDTH = 16
SPRITE_HEIGHT = 32

ANIM_IDLE = 0
ANIM_UPWALK = 1
ANIM_RIGHTWALK = 2
ANIM_DOWNWALK = 3
ANIM_LEFTWALK = 4
