# Game States
STARTUP = 0
MAIN_MENU = 1
MAIN_GAME = 2
CUTSCENE = 3
GAME_WIDTH = 640
GAME_HEIGHT = 360
LEVEL_WIDTH, LEVEL_HEIGHT = 320, 192
TILE_SIZE = 32

SPRITE_WIDTH = 16
SPRITE_HEIGHT = 32
SPRITE_COLL_WIDTH = 8
SPRITE_COLL_HEIGHT = 8

UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3

ANIM_UPIDLE = 0
ANIM_RIGHTIDLE = 1
ANIM_DOWNIDLE = 2
ANIM_LEFTIDLE = 3
ANIM_UPWALK = 4
ANIM_RIGHTWALK = 5
ANIM_DOWNWALK = 6
ANIM_LEFTWALK = 7

MAX_FEAR = 25000
START_FEAR = 20000
FEAR_PER_STEP = 5
