# Game States
STARTUP = 0
MAIN_MENU = 1
MAIN_GAME = 2
CUTSCENE = 3
GAME_OVER = 4
<<<<<<< HEAD
SKILLS_SCREEN = 5
=======
SKILL_SCREEN = 5
CREDITS = 6
>>>>>>> Start credits implementation

GAME_WIDTH = 1280
GAME_HEIGHT = 720
LEVEL_WIDTH, LEVEL_HEIGHT = 1280, 640
TILE_SIZE = 32

SPRITE_WIDTH = 16
SPRITE_HEIGHT = 32
SPRITE_COLL_WIDTH = 8
SPRITE_COLL_HEIGHT = 8

SELECTION_TOLERANCE = 10

UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3

ANIM_UPIDLE = 0
ANIM_RIGHTIDLE = 1
ANIM_DOWNIDLE = 2
ANIM_LEFTIDLE = 3
ANIM_UPWALK = 4
ANIM_RIGHTWALK = 5
ANIM_DOWNWALK = 6
ANIM_LEFTWALK = 7

TICKS_PER_FRAME = 4  # number of game frames for each sprite animation frame

MAX_FEAR = 25000
START_FEAR = 20000
FEAR_PER_STEP = 15
FEAR_PER_TICK = 30
POSSESSION_RANGE = 50

MUSIC_DIR = "music"
SOUND_DIR = "sound"

VIDEO_DIR = "video/"
SKILLS_FILE = "skills.json"

LEARNT_SKILL_COLOUR = (0, 150, 0)
CAN_BE_LEARNT_COLOUR = (0, 0, 150)
UNLEARNABLE_COLOUR = (150, 0, 0)
